name: Prisma Cloud Compute Image Scan

on: [push, pull_request]

env:
  # The Prisma Cloud Compute user
  # CI User (or Build and Deploy Security) role is recommended
  PCC_USER: ${{ secrets.PCC_USER }}
  PCC_PASS: ${{ secrets.PCC_PASS }}
  # The URL for the Prisma Cloud Compute Console (without a trailing /)
  PCC_CONSOLE_URL: ${{ secrets.PCC_CONSOLE_URL }}
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        # Defaults are sufficient generally
        # https://github.com/actions/checkout#usage

      - name: Build the image
        run: docker build -t $IMAGE_NAME .

      - name: Download twistcli from the Prisma Cloud Compute Console
        run: |
          curl --user $PCC_USER:$PCC_PASS --output ./twistcli $PCC_CONSOLE_URL/api/v1/util/twistcli
          chmod a+x ./twistcli

      - name: Scan the image
        run: ./twistcli images scan --address $PCC_CONSOLE_URL --user $PCC_USER --password $PCC_PASS --details $IMAGE_NAME
